import { Product } from './store'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Fresh Organic Apples',
    price: 4.99,
    image: '/products/apple.jpg',
    vendor: 'Green Valley Farms',
    vendorId: 'v1',
    category: 'Fruits',
    rating: 4.8,
    stock: 50,
    description: 'Premium organic apples sourced directly from local farms. Crisp, sweet, and perfect for snacking or baking.',
  },
  {
    id: '2',
    name: 'Organic Bananas',
    price: 2.99,
    image: '/products/banana.jpg',
    vendor: 'Green Valley Farms',
    vendorId: 'v1',
    category: 'Fruits',
    rating: 4.6,
    stock: 100,
    description: 'Ripe organic bananas, rich in potassium and perfect for smoothies or breakfast.',
  },
  {
    id: '3',
    name: 'Fresh Spinach Bundle',
    price: 3.49,
    image: '/products/spinach.jpg',
    vendor: 'Ocean Greens',
    vendorId: 'v2',
    category: 'Vegetables',
    rating: 4.7,
    stock: 30,
    description: 'Fresh organic spinach leaves, perfect for salads, smoothies, and cooking.',
  },
  {
    id: '4',
    name: 'Organic Carrots',
    price: 2.49,
    image: '/products/carrot.jpg',
    vendor: 'Ocean Greens',
    vendorId: 'v2',
    category: 'Vegetables',
    rating: 4.5,
    stock: 80,
    description: 'Crunchy organic carrots, great for snacking, cooking, or juicing.',
  },
  {
    id: '5',
    name: 'Whole Milk 1L',
    price: 3.99,
    image: '/products/milk.jpg',
    vendor: 'Dairy Fresh Co',
    vendorId: 'v3',
    category: 'Dairy',
    rating: 4.9,
    stock: 40,
    description: 'Fresh whole milk from grass-fed cows. Rich and creamy.',
  },
  {
    id: '6',
    name: 'Farm Fresh Eggs (12)',
    price: 5.99,
    image: '/products/eggs.jpg',
    vendor: 'Dairy Fresh Co',
    vendorId: 'v3',
    category: 'Dairy',
    rating: 4.8,
    stock: 60,
    description: 'Free-range eggs from happy chickens. Perfect for breakfast and baking.',
  },
  {
    id: '7',
    name: 'Sourdough Bread',
    price: 4.49,
    image: '/products/bread.jpg',
    vendor: 'Artisan Bakery',
    vendorId: 'v4',
    category: 'Bakery',
    rating: 4.7,
    stock: 25,
    description: 'Freshly baked sourdough bread with a crispy crust and soft interior.',
  },
  {
    id: '8',
    name: 'Atlantic Salmon Fillet',
    price: 12.99,
    image: '/products/salmon.jpg',
    vendor: 'Ocean Catch',
    vendorId: 'v5',
    category: 'Seafood',
    rating: 4.9,
    stock: 20,
    description: 'Fresh Atlantic salmon fillet, sustainably sourced and rich in omega-3.',
  },
  {
    id: '9',
    name: 'Organic Avocados (3)',
    price: 5.99,
    image: '/products/avocado.jpg',
    vendor: 'Green Valley Farms',
    vendorId: 'v1',
    category: 'Fruits',
    rating: 4.6,
    stock: 45,
    description: 'Creamy organic avocados, perfect for toast, salads, or guacamole.',
  },
  {
    id: '10',
    name: 'Greek Yogurt',
    price: 4.29,
    image: '/products/yogurt.jpg',
    vendor: 'Dairy Fresh Co',
    vendorId: 'v3',
    category: 'Dairy',
    rating: 4.7,
    stock: 35,
    description: 'Creamy Greek yogurt, high in protein and perfect for breakfast.',
  },
  {
    id: '11',
    name: 'Fresh Strawberries',
    price: 6.49,
    image: '/products/strawberry.jpg',
    vendor: 'Berry Farms',
    vendorId: 'v6',
    category: 'Fruits',
    rating: 4.8,
    stock: 40,
    description: 'Sweet and juicy strawberries, perfect for desserts or snacking.',
  },
  {
    id: '12',
    name: 'Chicken Breast',
    price: 8.99,
    image: '/products/chicken.jpg',
    vendor: 'Premium Meats',
    vendorId: 'v7',
    category: 'Meat',
    rating: 4.7,
    stock: 30,
    description: 'Lean chicken breast, hormone-free and perfect for healthy meals.',
  },
]

export const categories = [
  'All',
  'Fruits',
  'Vegetables',
  'Dairy',
  'Bakery',
  'Seafood',
  'Meat',
  'Pantry',
]

export const vendors = [
  { id: 'v1', name: 'Green Valley Farms', rating: 4.8, products: 45 },
  { id: 'v2', name: 'Ocean Greens', rating: 4.6, products: 32 },
  { id: 'v3', name: 'Dairy Fresh Co', rating: 4.9, products: 28 },
  { id: 'v4', name: 'Artisan Bakery', rating: 4.7, products: 15 },
  { id: 'v5', name: 'Ocean Catch', rating: 4.9, products: 22 },
  { id: 'v6', name: 'Berry Farms', rating: 4.8, products: 18 },
  { id: 'v7', name: 'Premium Meats', rating: 4.7, products: 25 },
]
